// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5R2JNEfWN9-xPCfa_ZyH7rxpt7tIzbnk',
    appId: '1:928270258852:web:7a54b1440725631ba64c31',
    messagingSenderId: '928270258852',
    projectId: 'tarvelapp-ed9e7',
    authDomain: 'tarvelapp-ed9e7.firebaseapp.com',
    databaseURL: 'https://tarvelapp-ed9e7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tarvelapp-ed9e7.firebasestorage.app',
    measurementId: 'G-FE8WKPQFV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOST62YOhx-evm6t8b_zq5Y524vJ6XBSE',
    appId: '1:928270258852:android:88bf7ce93264523da64c31',
    messagingSenderId: '928270258852',
    projectId: 'tarvelapp-ed9e7',
    databaseURL: 'https://tarvelapp-ed9e7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tarvelapp-ed9e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFs4oGzP-NHtPZbj77RiRG7WvHiZtITco',
    appId: '1:928270258852:ios:5c750d9c3fd34052a64c31',
    messagingSenderId: '928270258852',
    projectId: 'tarvelapp-ed9e7',
    databaseURL: 'https://tarvelapp-ed9e7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tarvelapp-ed9e7.firebasestorage.app',
    iosBundleId: 'com.example.projectApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFs4oGzP-NHtPZbj77RiRG7WvHiZtITco',
    appId: '1:928270258852:ios:5c750d9c3fd34052a64c31',
    messagingSenderId: '928270258852',
    projectId: 'tarvelapp-ed9e7',
    databaseURL: 'https://tarvelapp-ed9e7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tarvelapp-ed9e7.firebasestorage.app',
    iosBundleId: 'com.example.projectApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5R2JNEfWN9-xPCfa_ZyH7rxpt7tIzbnk',
    appId: '1:928270258852:web:f4121f8f83b7f0b9a64c31',
    messagingSenderId: '928270258852',
    projectId: 'tarvelapp-ed9e7',
    authDomain: 'tarvelapp-ed9e7.firebaseapp.com',
    databaseURL: 'https://tarvelapp-ed9e7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tarvelapp-ed9e7.firebasestorage.app',
    measurementId: 'G-DG65RDC9DW',
  );
}
